### ISSUE TITLE
Change the order in which data from modules is displayed

### ISSUE THREAD

**Issue by Laz2516** [CFenner/MMM-Netatmo#150]
Tell me how to change the display order of modules? I have a main module, a rain module, an outdoor (external) module, three internal (indoor) modules.
The order is now displayed:
the main
external (outdoor)
rain
internal 1  (indoor)
internal 2  (indoor)
internal 3  (indoor)

The same display order is in the web interface of the weather station.
In the netatmo.js file, I did not change anything in the names of the modules.

moduleType: {
    MAIN: 'NAMain',
    INDOOR: 'NAModule4',
    OUTDOOR: 'NAModule1',
    RAIN: 'NAModule3',
    WIND: 'NAModule2',
 },

I tried to add a string in config.js -

moduleOrder: ["NAModule1", "NAModule3", "NAModule2", "NAMain", "NAModule4" ],

but then the data mapping does not work.

**Comment by Laz2516** [comment]
Good afternoon! Please help change the display order of the modules.....))

**Comment by CFenner** [comment]
Please use the [config option `dataOrder` and `moduleOrder`](https://github.com/CFenner/MMM-Netatmo#config-options) to rearrange. Use the displayed module names and the english measurement names for filtering.

<img width="307" alt="Bildschirmfoto 2023-08-15 um 15 13 54" src="https://github.com/CFenner/MMM-Netatmo/assets/9592452/0c22ecc5-ab5a-455d-afdc-cd5a601a56e6">

```yml

      header: 'Netatmo',
      config: {
        moduleOrder: ["Hamburg - Arbeitszimmer", "NAModule3", "NAModule2", "NAMain", "NAModule4" ],
```
